export const FETCH_DATA = 'FETCH_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_DELETE = 'FETCH_DATA_DELETE';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_DATA_REQUEST = 'UPDATE_DATA_REQUEST';